### ISSUE TITLE
I帧是帧组GOP的基础帧(第一帧),在一组中只有一个I帧;？

### ISSUE THREAD

**Issue by shenleilei** [gongluck/AnalysisAVP#1]
你好。从定义来看，每个GOP的第一帧应该是IDR帧吧；每个GOP中应该是只有一个IDR帧，普通I帧可能不止一个。

**Comment by gongluck** [comment]
已更改为”IDR帧是帧组GOP的基础帧(第一个(I)帧),在一组GOP中只有一个IDR帧;“
